name: Build

on:
  pull_request:
    branches:
      "main"
  push:
    branches:
      "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: https://allure.autotests.cloud
          allure-token: ${{ secret.ALLURE_TOKEN }}
          allure-project-id: 2214
      - uses: Xotabu4/selenoid-github-action@v2
      - run: allurectl watch -- ./gradlew clean test
        env:
          ALLURE_RESULTS: build/allure-results
